# Generated by Django 4.1.7 on 2023-03-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credits", "0001_initial"),
        ("deposits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveBigIntegerField()),
                ("cvv", models.CharField(max_length=100)),
                ("data", models.CharField(max_length=100)),
                ("balance", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("login", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                (
                    "card",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.card",
                    ),
                ),
                (
                    "credit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="credits.credit",
                    ),
                ),
                (
                    "deposit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="deposits.deposit",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
