# Generated by Django 4.1.7 on 2023-05-24 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_card_number_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deposit',
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
