# Generated by Django 4.1.7 on 2023-05-24 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_card_remove_user_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
