# Generated by Django 4.1.7 on 2023-03-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='addres',
            new_name='address',
        ),
    ]
